"""Stable failure codes for public verification and reconciliation."""

from __future__ import annotations

from enum import Enum


class FailureCode(str, Enum):
    INVALID_JSON = "INVALID_JSON"
    DUPLICATE_JSON_KEY = "DUPLICATE_JSON_KEY"
    NON_FINITE_JSON_NUMBER = "NON_FINITE_JSON_NUMBER"
    SCHEMA_INVALID = "SCHEMA_INVALID"
    UNSUPPORTED_PROFILE = "UNSUPPORTED_PROFILE"
    UNSUPPORTED_ALGORITHM = "UNSUPPORTED_ALGORITHM"
    SIGNATURE_INVALID = "SIGNATURE_INVALID"
    KEY_ID_MISMATCH = "KEY_ID_MISMATCH"
    PUBLIC_KEY_FINGERPRINT_MISMATCH = "PUBLIC_KEY_FINGERPRINT_MISMATCH"
    POLICY_BINDING_MISMATCH = "POLICY_BINDING_MISMATCH"
    BUILD_BINDING_MISMATCH = "BUILD_BINDING_MISMATCH"
    IMAGE_BINDING_MISMATCH = "IMAGE_BINDING_MISMATCH"
    CONFIG_BINDING_MISMATCH = "CONFIG_BINDING_MISMATCH"
    REQUIRED_FIELD_MISSING = "REQUIRED_FIELD_MISSING"
    RECONCILIATION_INCOMPLETE = "RECONCILIATION_INCOMPLETE"
